# This is a basic workflow to help you get started with Actions

name: test &d eploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: npm install
      - name: test
        run: npm test

  deploy-doc:
    needs: test
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: build gh page
        run: |
          npm install
          npm run doc:build

      - name: deploy gh page
        uses: Cecilapp/GitHub-Pages-deploy@master
        env:
          EMAIL: 545360100@qq.com # must be a verified email
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }} # https://github.com/settings/tokens
          BUILD_DIR: .doc/ # "_site/" by default

  deploy-npm:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: build package
        run: |
          npm install
          npm run build

      - name: deploy npm
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
